// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging/response/payload/endpoint/capability.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "messaging/response/payload/endpoint/capability.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace agrirouter {
namespace response {
namespace payload {
namespace endpoint {

namespace {

const ::google::protobuf::Descriptor* CapabilityResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CapabilityResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* CapabilityResponse_Recipient_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CapabilityResponse_Recipient_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto() {
  protobuf_AddDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "messaging/response/payload/endpoint/capability.proto");
  GOOGLE_CHECK(file != NULL);
  CapabilityResponse_descriptor_ = file->message_type(0);
  static const int CapabilityResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CapabilityResponse, application_message_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CapabilityResponse, recipients_),
  };
  CapabilityResponse_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CapabilityResponse_descriptor_,
      CapabilityResponse::internal_default_instance(),
      CapabilityResponse_offsets_,
      -1,
      -1,
      -1,
      sizeof(CapabilityResponse),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CapabilityResponse, _internal_metadata_));
  CapabilityResponse_Recipient_descriptor_ = CapabilityResponse_descriptor_->nested_type(0);
  static const int CapabilityResponse_Recipient_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CapabilityResponse_Recipient, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CapabilityResponse_Recipient, technical_message_type_),
  };
  CapabilityResponse_Recipient_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CapabilityResponse_Recipient_descriptor_,
      CapabilityResponse_Recipient::internal_default_instance(),
      CapabilityResponse_Recipient_offsets_,
      -1,
      -1,
      -1,
      sizeof(CapabilityResponse_Recipient),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CapabilityResponse_Recipient, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CapabilityResponse_descriptor_, CapabilityResponse::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CapabilityResponse_Recipient_descriptor_, CapabilityResponse_Recipient::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto() {
  CapabilityResponse_default_instance_.Shutdown();
  delete CapabilityResponse_reflection_;
  CapabilityResponse_Recipient_default_instance_.Shutdown();
  delete CapabilityResponse_Recipient_reflection_;
}

void protobuf_InitDefaults_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  CapabilityResponse_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString();
  CapabilityResponse_Recipient_default_instance_.DefaultConstruct();
  CapabilityResponse_default_instance_.get_mutable()->InitAsDefaultInstance();
  CapabilityResponse_Recipient_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto_once_);
void protobuf_InitDefaults_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto_once_,
                 &protobuf_InitDefaults_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto_impl);
}
void protobuf_AddDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n4messaging/response/payload/endpoint/ca"
    "pability.proto\022$agrirouter.response.payl"
    "oad.endpoint\"\305\001\n\022CapabilityResponse\022\036\n\026a"
    "pplication_message_id\030\001 \001(\t\022V\n\nrecipient"
    "s\030\002 \003(\0132B.agrirouter.response.payload.en"
    "dpoint.CapabilityResponse.Recipient\0327\n\tR"
    "ecipient\022\n\n\002id\030\001 \001(\t\022\036\n\026technical_messag"
    "e_type\030\002 \003(\tb\006proto3", 300);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "messaging/response/payload/endpoint/capability.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto_once_);
void protobuf_AddDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto_once_,
                 &protobuf_AddDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto {
  StaticDescriptorInitializer_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto() {
    protobuf_AddDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto();
  }
} static_descriptor_initializer_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CapabilityResponse_Recipient::kIdFieldNumber;
const int CapabilityResponse_Recipient::kTechnicalMessageTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CapabilityResponse_Recipient::CapabilityResponse_Recipient()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
}

void CapabilityResponse_Recipient::InitAsDefaultInstance() {
}

CapabilityResponse_Recipient::CapabilityResponse_Recipient(const CapabilityResponse_Recipient& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
}

void CapabilityResponse_Recipient::SharedCtor() {
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

CapabilityResponse_Recipient::~CapabilityResponse_Recipient() {
  // @@protoc_insertion_point(destructor:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
  SharedDtor();
}

void CapabilityResponse_Recipient::SharedDtor() {
  id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CapabilityResponse_Recipient::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CapabilityResponse_Recipient::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CapabilityResponse_Recipient_descriptor_;
}

const CapabilityResponse_Recipient& CapabilityResponse_Recipient::default_instance() {
  protobuf_InitDefaults_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<CapabilityResponse_Recipient> CapabilityResponse_Recipient_default_instance_;

CapabilityResponse_Recipient* CapabilityResponse_Recipient::New(::google::protobuf::Arena* arena) const {
  CapabilityResponse_Recipient* n = new CapabilityResponse_Recipient;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CapabilityResponse_Recipient::Clear() {
// @@protoc_insertion_point(message_clear_start:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  technical_message_type_.Clear();
}

bool CapabilityResponse_Recipient::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string id = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->id().data(), this->id().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_technical_message_type;
        break;
      }

      // repeated string technical_message_type = 2;
      case 2: {
        if (tag == 18) {
         parse_technical_message_type:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_technical_message_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->technical_message_type(this->technical_message_type_size() - 1).data(),
            this->technical_message_type(this->technical_message_type_size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_technical_message_type;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
  return false;
#undef DO_
}

void CapabilityResponse_Recipient::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
  // optional string id = 1;
  if (this->id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->id(), output);
  }

  // repeated string technical_message_type = 2;
  for (int i = 0; i < this->technical_message_type_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->technical_message_type(i).data(), this->technical_message_type(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->technical_message_type(i), output);
  }

  // @@protoc_insertion_point(serialize_end:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
}

::google::protobuf::uint8* CapabilityResponse_Recipient::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
  // optional string id = 1;
  if (this->id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->id(), target);
  }

  // repeated string technical_message_type = 2;
  for (int i = 0; i < this->technical_message_type_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->technical_message_type(i).data(), this->technical_message_type(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->technical_message_type(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
  return target;
}

size_t CapabilityResponse_Recipient::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
  size_t total_size = 0;

  // optional string id = 1;
  if (this->id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->id());
  }

  // repeated string technical_message_type = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->technical_message_type_size());
  for (int i = 0; i < this->technical_message_type_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->technical_message_type(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CapabilityResponse_Recipient::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CapabilityResponse_Recipient* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CapabilityResponse_Recipient>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
    UnsafeMergeFrom(*source);
  }
}

void CapabilityResponse_Recipient::MergeFrom(const CapabilityResponse_Recipient& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void CapabilityResponse_Recipient::UnsafeMergeFrom(const CapabilityResponse_Recipient& from) {
  GOOGLE_DCHECK(&from != this);
  technical_message_type_.UnsafeMergeFrom(from.technical_message_type_);
  if (from.id().size() > 0) {

    id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.id_);
  }
}

void CapabilityResponse_Recipient::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CapabilityResponse_Recipient::CopyFrom(const CapabilityResponse_Recipient& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool CapabilityResponse_Recipient::IsInitialized() const {

  return true;
}

void CapabilityResponse_Recipient::Swap(CapabilityResponse_Recipient* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CapabilityResponse_Recipient::InternalSwap(CapabilityResponse_Recipient* other) {
  id_.Swap(&other->id_);
  technical_message_type_.UnsafeArenaSwap(&other->technical_message_type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CapabilityResponse_Recipient::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CapabilityResponse_Recipient_descriptor_;
  metadata.reflection = CapabilityResponse_Recipient_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CapabilityResponse::kApplicationMessageIdFieldNumber;
const int CapabilityResponse::kRecipientsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CapabilityResponse::CapabilityResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:agrirouter.response.payload.endpoint.CapabilityResponse)
}

void CapabilityResponse::InitAsDefaultInstance() {
}

CapabilityResponse::CapabilityResponse(const CapabilityResponse& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:agrirouter.response.payload.endpoint.CapabilityResponse)
}

void CapabilityResponse::SharedCtor() {
  application_message_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

CapabilityResponse::~CapabilityResponse() {
  // @@protoc_insertion_point(destructor:agrirouter.response.payload.endpoint.CapabilityResponse)
  SharedDtor();
}

void CapabilityResponse::SharedDtor() {
  application_message_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CapabilityResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CapabilityResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CapabilityResponse_descriptor_;
}

const CapabilityResponse& CapabilityResponse::default_instance() {
  protobuf_InitDefaults_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<CapabilityResponse> CapabilityResponse_default_instance_;

CapabilityResponse* CapabilityResponse::New(::google::protobuf::Arena* arena) const {
  CapabilityResponse* n = new CapabilityResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CapabilityResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:agrirouter.response.payload.endpoint.CapabilityResponse)
  application_message_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  recipients_.Clear();
}

bool CapabilityResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:agrirouter.response.payload.endpoint.CapabilityResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string application_message_id = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_application_message_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->application_message_id().data(), this->application_message_id().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_recipients;
        break;
      }

      // repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;
      case 2: {
        if (tag == 18) {
         parse_recipients:
          DO_(input->IncrementRecursionDepth());
         parse_loop_recipients:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_recipients()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_recipients;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:agrirouter.response.payload.endpoint.CapabilityResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:agrirouter.response.payload.endpoint.CapabilityResponse)
  return false;
#undef DO_
}

void CapabilityResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:agrirouter.response.payload.endpoint.CapabilityResponse)
  // optional string application_message_id = 1;
  if (this->application_message_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->application_message_id().data(), this->application_message_id().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->application_message_id(), output);
  }

  // repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;
  for (unsigned int i = 0, n = this->recipients_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->recipients(i), output);
  }

  // @@protoc_insertion_point(serialize_end:agrirouter.response.payload.endpoint.CapabilityResponse)
}

::google::protobuf::uint8* CapabilityResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:agrirouter.response.payload.endpoint.CapabilityResponse)
  // optional string application_message_id = 1;
  if (this->application_message_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->application_message_id().data(), this->application_message_id().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->application_message_id(), target);
  }

  // repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;
  for (unsigned int i = 0, n = this->recipients_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->recipients(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:agrirouter.response.payload.endpoint.CapabilityResponse)
  return target;
}

size_t CapabilityResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:agrirouter.response.payload.endpoint.CapabilityResponse)
  size_t total_size = 0;

  // optional string application_message_id = 1;
  if (this->application_message_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->application_message_id());
  }

  // repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;
  {
    unsigned int count = this->recipients_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->recipients(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CapabilityResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:agrirouter.response.payload.endpoint.CapabilityResponse)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CapabilityResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CapabilityResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:agrirouter.response.payload.endpoint.CapabilityResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:agrirouter.response.payload.endpoint.CapabilityResponse)
    UnsafeMergeFrom(*source);
  }
}

void CapabilityResponse::MergeFrom(const CapabilityResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:agrirouter.response.payload.endpoint.CapabilityResponse)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void CapabilityResponse::UnsafeMergeFrom(const CapabilityResponse& from) {
  GOOGLE_DCHECK(&from != this);
  recipients_.MergeFrom(from.recipients_);
  if (from.application_message_id().size() > 0) {

    application_message_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.application_message_id_);
  }
}

void CapabilityResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:agrirouter.response.payload.endpoint.CapabilityResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CapabilityResponse::CopyFrom(const CapabilityResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:agrirouter.response.payload.endpoint.CapabilityResponse)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool CapabilityResponse::IsInitialized() const {

  return true;
}

void CapabilityResponse::Swap(CapabilityResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CapabilityResponse::InternalSwap(CapabilityResponse* other) {
  application_message_id_.Swap(&other->application_message_id_);
  recipients_.UnsafeArenaSwap(&other->recipients_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CapabilityResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CapabilityResponse_descriptor_;
  metadata.reflection = CapabilityResponse_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CapabilityResponse_Recipient

// optional string id = 1;
void CapabilityResponse_Recipient::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CapabilityResponse_Recipient::id() const {
  // @@protoc_insertion_point(field_get:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CapabilityResponse_Recipient::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id)
}
void CapabilityResponse_Recipient::set_id(const char* value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id)
}
void CapabilityResponse_Recipient::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id)
}
::std::string* CapabilityResponse_Recipient::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CapabilityResponse_Recipient::release_id() {
  // @@protoc_insertion_point(field_release:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CapabilityResponse_Recipient::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id)
}

// repeated string technical_message_type = 2;
int CapabilityResponse_Recipient::technical_message_type_size() const {
  return technical_message_type_.size();
}
void CapabilityResponse_Recipient::clear_technical_message_type() {
  technical_message_type_.Clear();
}
const ::std::string& CapabilityResponse_Recipient::technical_message_type(int index) const {
  // @@protoc_insertion_point(field_get:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
  return technical_message_type_.Get(index);
}
::std::string* CapabilityResponse_Recipient::mutable_technical_message_type(int index) {
  // @@protoc_insertion_point(field_mutable:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
  return technical_message_type_.Mutable(index);
}
void CapabilityResponse_Recipient::set_technical_message_type(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
  technical_message_type_.Mutable(index)->assign(value);
}
void CapabilityResponse_Recipient::set_technical_message_type(int index, const char* value) {
  technical_message_type_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
}
void CapabilityResponse_Recipient::set_technical_message_type(int index, const char* value, size_t size) {
  technical_message_type_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
}
::std::string* CapabilityResponse_Recipient::add_technical_message_type() {
  // @@protoc_insertion_point(field_add_mutable:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
  return technical_message_type_.Add();
}
void CapabilityResponse_Recipient::add_technical_message_type(const ::std::string& value) {
  technical_message_type_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
}
void CapabilityResponse_Recipient::add_technical_message_type(const char* value) {
  technical_message_type_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
}
void CapabilityResponse_Recipient::add_technical_message_type(const char* value, size_t size) {
  technical_message_type_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
CapabilityResponse_Recipient::technical_message_type() const {
  // @@protoc_insertion_point(field_list:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
  return technical_message_type_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
CapabilityResponse_Recipient::mutable_technical_message_type() {
  // @@protoc_insertion_point(field_mutable_list:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
  return &technical_message_type_;
}

inline const CapabilityResponse_Recipient* CapabilityResponse_Recipient::internal_default_instance() {
  return &CapabilityResponse_Recipient_default_instance_.get();
}
// -------------------------------------------------------------------

// CapabilityResponse

// optional string application_message_id = 1;
void CapabilityResponse::clear_application_message_id() {
  application_message_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CapabilityResponse::application_message_id() const {
  // @@protoc_insertion_point(field_get:agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id)
  return application_message_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CapabilityResponse::set_application_message_id(const ::std::string& value) {
  
  application_message_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id)
}
void CapabilityResponse::set_application_message_id(const char* value) {
  
  application_message_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id)
}
void CapabilityResponse::set_application_message_id(const char* value, size_t size) {
  
  application_message_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id)
}
::std::string* CapabilityResponse::mutable_application_message_id() {
  
  // @@protoc_insertion_point(field_mutable:agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id)
  return application_message_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CapabilityResponse::release_application_message_id() {
  // @@protoc_insertion_point(field_release:agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id)
  
  return application_message_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CapabilityResponse::set_allocated_application_message_id(::std::string* application_message_id) {
  if (application_message_id != NULL) {
    
  } else {
    
  }
  application_message_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), application_message_id);
  // @@protoc_insertion_point(field_set_allocated:agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id)
}

// repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;
int CapabilityResponse::recipients_size() const {
  return recipients_.size();
}
void CapabilityResponse::clear_recipients() {
  recipients_.Clear();
}
const ::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient& CapabilityResponse::recipients(int index) const {
  // @@protoc_insertion_point(field_get:agrirouter.response.payload.endpoint.CapabilityResponse.recipients)
  return recipients_.Get(index);
}
::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient* CapabilityResponse::mutable_recipients(int index) {
  // @@protoc_insertion_point(field_mutable:agrirouter.response.payload.endpoint.CapabilityResponse.recipients)
  return recipients_.Mutable(index);
}
::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient* CapabilityResponse::add_recipients() {
  // @@protoc_insertion_point(field_add:agrirouter.response.payload.endpoint.CapabilityResponse.recipients)
  return recipients_.Add();
}
::google::protobuf::RepeatedPtrField< ::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient >*
CapabilityResponse::mutable_recipients() {
  // @@protoc_insertion_point(field_mutable_list:agrirouter.response.payload.endpoint.CapabilityResponse.recipients)
  return &recipients_;
}
const ::google::protobuf::RepeatedPtrField< ::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient >&
CapabilityResponse::recipients() const {
  // @@protoc_insertion_point(field_list:agrirouter.response.payload.endpoint.CapabilityResponse.recipients)
  return recipients_;
}

inline const CapabilityResponse* CapabilityResponse::internal_default_instance() {
  return &CapabilityResponse_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace endpoint
}  // namespace payload
}  // namespace response
}  // namespace agrirouter

// @@protoc_insertion_point(global_scope)
