// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging/request/payload/endpoint/subscription.proto

#ifndef PROTOBUF_messaging_2frequest_2fpayload_2fendpoint_2fsubscription_2eproto__INCLUDED
#define PROTOBUF_messaging_2frequest_2fpayload_2fendpoint_2fsubscription_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace agrirouter {
namespace request {
namespace payload {
namespace endpoint {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_messaging_2frequest_2fpayload_2fendpoint_2fsubscription_2eproto();
void protobuf_InitDefaults_messaging_2frequest_2fpayload_2fendpoint_2fsubscription_2eproto();
void protobuf_AssignDesc_messaging_2frequest_2fpayload_2fendpoint_2fsubscription_2eproto();
void protobuf_ShutdownFile_messaging_2frequest_2fpayload_2fendpoint_2fsubscription_2eproto();

class Subscription;
class Subscription_MessageTypeSubscriptionItem;

// ===================================================================

class Subscription_MessageTypeSubscriptionItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem) */ {
 public:
  Subscription_MessageTypeSubscriptionItem();
  virtual ~Subscription_MessageTypeSubscriptionItem();

  Subscription_MessageTypeSubscriptionItem(const Subscription_MessageTypeSubscriptionItem& from);

  inline Subscription_MessageTypeSubscriptionItem& operator=(const Subscription_MessageTypeSubscriptionItem& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Subscription_MessageTypeSubscriptionItem& default_instance();

  static const Subscription_MessageTypeSubscriptionItem* internal_default_instance();

  void Swap(Subscription_MessageTypeSubscriptionItem* other);

  // implements Message ----------------------------------------------

  inline Subscription_MessageTypeSubscriptionItem* New() const { return New(NULL); }

  Subscription_MessageTypeSubscriptionItem* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Subscription_MessageTypeSubscriptionItem& from);
  void MergeFrom(const Subscription_MessageTypeSubscriptionItem& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Subscription_MessageTypeSubscriptionItem* other);
  void UnsafeMergeFrom(const Subscription_MessageTypeSubscriptionItem& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string technical_message_type = 1;
  void clear_technical_message_type();
  static const int kTechnicalMessageTypeFieldNumber = 1;
  const ::std::string& technical_message_type() const;
  void set_technical_message_type(const ::std::string& value);
  void set_technical_message_type(const char* value);
  void set_technical_message_type(const char* value, size_t size);
  ::std::string* mutable_technical_message_type();
  ::std::string* release_technical_message_type();
  void set_allocated_technical_message_type(::std::string* technical_message_type);

  // repeated uint32 ddis = 2;
  int ddis_size() const;
  void clear_ddis();
  static const int kDdisFieldNumber = 2;
  ::google::protobuf::uint32 ddis(int index) const;
  void set_ddis(int index, ::google::protobuf::uint32 value);
  void add_ddis(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      ddis() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_ddis();

  // optional bool position = 3;
  void clear_position();
  static const int kPositionFieldNumber = 3;
  bool position() const;
  void set_position(bool value);

  // @@protoc_insertion_point(class_scope:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > ddis_;
  mutable int _ddis_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr technical_message_type_;
  bool position_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_messaging_2frequest_2fpayload_2fendpoint_2fsubscription_2eproto_impl();
  friend void  protobuf_AddDesc_messaging_2frequest_2fpayload_2fendpoint_2fsubscription_2eproto_impl();
  friend void protobuf_AssignDesc_messaging_2frequest_2fpayload_2fendpoint_2fsubscription_2eproto();
  friend void protobuf_ShutdownFile_messaging_2frequest_2fpayload_2fendpoint_2fsubscription_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Subscription_MessageTypeSubscriptionItem> Subscription_MessageTypeSubscriptionItem_default_instance_;

// -------------------------------------------------------------------

class Subscription : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agrirouter.request.payload.endpoint.Subscription) */ {
 public:
  Subscription();
  virtual ~Subscription();

  Subscription(const Subscription& from);

  inline Subscription& operator=(const Subscription& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Subscription& default_instance();

  static const Subscription* internal_default_instance();

  void Swap(Subscription* other);

  // implements Message ----------------------------------------------

  inline Subscription* New() const { return New(NULL); }

  Subscription* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Subscription& from);
  void MergeFrom(const Subscription& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Subscription* other);
  void UnsafeMergeFrom(const Subscription& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Subscription_MessageTypeSubscriptionItem MessageTypeSubscriptionItem;

  // accessors -------------------------------------------------------

  // repeated .agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem technical_message_types = 1;
  int technical_message_types_size() const;
  void clear_technical_message_types();
  static const int kTechnicalMessageTypesFieldNumber = 1;
  const ::agrirouter::request::payload::endpoint::Subscription_MessageTypeSubscriptionItem& technical_message_types(int index) const;
  ::agrirouter::request::payload::endpoint::Subscription_MessageTypeSubscriptionItem* mutable_technical_message_types(int index);
  ::agrirouter::request::payload::endpoint::Subscription_MessageTypeSubscriptionItem* add_technical_message_types();
  ::google::protobuf::RepeatedPtrField< ::agrirouter::request::payload::endpoint::Subscription_MessageTypeSubscriptionItem >*
      mutable_technical_message_types();
  const ::google::protobuf::RepeatedPtrField< ::agrirouter::request::payload::endpoint::Subscription_MessageTypeSubscriptionItem >&
      technical_message_types() const;

  // @@protoc_insertion_point(class_scope:agrirouter.request.payload.endpoint.Subscription)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::agrirouter::request::payload::endpoint::Subscription_MessageTypeSubscriptionItem > technical_message_types_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_messaging_2frequest_2fpayload_2fendpoint_2fsubscription_2eproto_impl();
  friend void  protobuf_AddDesc_messaging_2frequest_2fpayload_2fendpoint_2fsubscription_2eproto_impl();
  friend void protobuf_AssignDesc_messaging_2frequest_2fpayload_2fendpoint_2fsubscription_2eproto();
  friend void protobuf_ShutdownFile_messaging_2frequest_2fpayload_2fendpoint_2fsubscription_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Subscription> Subscription_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Subscription_MessageTypeSubscriptionItem

// optional string technical_message_type = 1;
inline void Subscription_MessageTypeSubscriptionItem::clear_technical_message_type() {
  technical_message_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Subscription_MessageTypeSubscriptionItem::technical_message_type() const {
  // @@protoc_insertion_point(field_get:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem.technical_message_type)
  return technical_message_type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Subscription_MessageTypeSubscriptionItem::set_technical_message_type(const ::std::string& value) {
  
  technical_message_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem.technical_message_type)
}
inline void Subscription_MessageTypeSubscriptionItem::set_technical_message_type(const char* value) {
  
  technical_message_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem.technical_message_type)
}
inline void Subscription_MessageTypeSubscriptionItem::set_technical_message_type(const char* value, size_t size) {
  
  technical_message_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem.technical_message_type)
}
inline ::std::string* Subscription_MessageTypeSubscriptionItem::mutable_technical_message_type() {
  
  // @@protoc_insertion_point(field_mutable:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem.technical_message_type)
  return technical_message_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Subscription_MessageTypeSubscriptionItem::release_technical_message_type() {
  // @@protoc_insertion_point(field_release:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem.technical_message_type)
  
  return technical_message_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Subscription_MessageTypeSubscriptionItem::set_allocated_technical_message_type(::std::string* technical_message_type) {
  if (technical_message_type != NULL) {
    
  } else {
    
  }
  technical_message_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), technical_message_type);
  // @@protoc_insertion_point(field_set_allocated:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem.technical_message_type)
}

// repeated uint32 ddis = 2;
inline int Subscription_MessageTypeSubscriptionItem::ddis_size() const {
  return ddis_.size();
}
inline void Subscription_MessageTypeSubscriptionItem::clear_ddis() {
  ddis_.Clear();
}
inline ::google::protobuf::uint32 Subscription_MessageTypeSubscriptionItem::ddis(int index) const {
  // @@protoc_insertion_point(field_get:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem.ddis)
  return ddis_.Get(index);
}
inline void Subscription_MessageTypeSubscriptionItem::set_ddis(int index, ::google::protobuf::uint32 value) {
  ddis_.Set(index, value);
  // @@protoc_insertion_point(field_set:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem.ddis)
}
inline void Subscription_MessageTypeSubscriptionItem::add_ddis(::google::protobuf::uint32 value) {
  ddis_.Add(value);
  // @@protoc_insertion_point(field_add:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem.ddis)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
Subscription_MessageTypeSubscriptionItem::ddis() const {
  // @@protoc_insertion_point(field_list:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem.ddis)
  return ddis_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
Subscription_MessageTypeSubscriptionItem::mutable_ddis() {
  // @@protoc_insertion_point(field_mutable_list:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem.ddis)
  return &ddis_;
}

// optional bool position = 3;
inline void Subscription_MessageTypeSubscriptionItem::clear_position() {
  position_ = false;
}
inline bool Subscription_MessageTypeSubscriptionItem::position() const {
  // @@protoc_insertion_point(field_get:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem.position)
  return position_;
}
inline void Subscription_MessageTypeSubscriptionItem::set_position(bool value) {
  
  position_ = value;
  // @@protoc_insertion_point(field_set:agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem.position)
}

inline const Subscription_MessageTypeSubscriptionItem* Subscription_MessageTypeSubscriptionItem::internal_default_instance() {
  return &Subscription_MessageTypeSubscriptionItem_default_instance_.get();
}
// -------------------------------------------------------------------

// Subscription

// repeated .agrirouter.request.payload.endpoint.Subscription.MessageTypeSubscriptionItem technical_message_types = 1;
inline int Subscription::technical_message_types_size() const {
  return technical_message_types_.size();
}
inline void Subscription::clear_technical_message_types() {
  technical_message_types_.Clear();
}
inline const ::agrirouter::request::payload::endpoint::Subscription_MessageTypeSubscriptionItem& Subscription::technical_message_types(int index) const {
  // @@protoc_insertion_point(field_get:agrirouter.request.payload.endpoint.Subscription.technical_message_types)
  return technical_message_types_.Get(index);
}
inline ::agrirouter::request::payload::endpoint::Subscription_MessageTypeSubscriptionItem* Subscription::mutable_technical_message_types(int index) {
  // @@protoc_insertion_point(field_mutable:agrirouter.request.payload.endpoint.Subscription.technical_message_types)
  return technical_message_types_.Mutable(index);
}
inline ::agrirouter::request::payload::endpoint::Subscription_MessageTypeSubscriptionItem* Subscription::add_technical_message_types() {
  // @@protoc_insertion_point(field_add:agrirouter.request.payload.endpoint.Subscription.technical_message_types)
  return technical_message_types_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::agrirouter::request::payload::endpoint::Subscription_MessageTypeSubscriptionItem >*
Subscription::mutable_technical_message_types() {
  // @@protoc_insertion_point(field_mutable_list:agrirouter.request.payload.endpoint.Subscription.technical_message_types)
  return &technical_message_types_;
}
inline const ::google::protobuf::RepeatedPtrField< ::agrirouter::request::payload::endpoint::Subscription_MessageTypeSubscriptionItem >&
Subscription::technical_message_types() const {
  // @@protoc_insertion_point(field_list:agrirouter.request.payload.endpoint.Subscription.technical_message_types)
  return technical_message_types_;
}

inline const Subscription* Subscription::internal_default_instance() {
  return &Subscription_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace endpoint
}  // namespace payload
}  // namespace request
}  // namespace agrirouter

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_messaging_2frequest_2fpayload_2fendpoint_2fsubscription_2eproto__INCLUDED
