// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging/response/payload/endpoint/capability.proto

#ifndef PROTOBUF_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto__INCLUDED
#define PROTOBUF_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace agrirouter {
namespace response {
namespace payload {
namespace endpoint {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto();
void protobuf_InitDefaults_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto();
void protobuf_AssignDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto();
void protobuf_ShutdownFile_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto();

class CapabilityResponse;
class CapabilityResponse_Recipient;

// ===================================================================

class CapabilityResponse_Recipient : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient) */ {
 public:
  CapabilityResponse_Recipient();
  virtual ~CapabilityResponse_Recipient();

  CapabilityResponse_Recipient(const CapabilityResponse_Recipient& from);

  inline CapabilityResponse_Recipient& operator=(const CapabilityResponse_Recipient& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CapabilityResponse_Recipient& default_instance();

  static const CapabilityResponse_Recipient* internal_default_instance();

  void Swap(CapabilityResponse_Recipient* other);

  // implements Message ----------------------------------------------

  inline CapabilityResponse_Recipient* New() const { return New(NULL); }

  CapabilityResponse_Recipient* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CapabilityResponse_Recipient& from);
  void MergeFrom(const CapabilityResponse_Recipient& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CapabilityResponse_Recipient* other);
  void UnsafeMergeFrom(const CapabilityResponse_Recipient& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // repeated string technical_message_type = 2;
  int technical_message_type_size() const;
  void clear_technical_message_type();
  static const int kTechnicalMessageTypeFieldNumber = 2;
  const ::std::string& technical_message_type(int index) const;
  ::std::string* mutable_technical_message_type(int index);
  void set_technical_message_type(int index, const ::std::string& value);
  void set_technical_message_type(int index, const char* value);
  void set_technical_message_type(int index, const char* value, size_t size);
  ::std::string* add_technical_message_type();
  void add_technical_message_type(const ::std::string& value);
  void add_technical_message_type(const char* value);
  void add_technical_message_type(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& technical_message_type() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_technical_message_type();

  // @@protoc_insertion_point(class_scope:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> technical_message_type_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto_impl();
  friend void  protobuf_AddDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto_impl();
  friend void protobuf_AssignDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto();
  friend void protobuf_ShutdownFile_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<CapabilityResponse_Recipient> CapabilityResponse_Recipient_default_instance_;

// -------------------------------------------------------------------

class CapabilityResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agrirouter.response.payload.endpoint.CapabilityResponse) */ {
 public:
  CapabilityResponse();
  virtual ~CapabilityResponse();

  CapabilityResponse(const CapabilityResponse& from);

  inline CapabilityResponse& operator=(const CapabilityResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CapabilityResponse& default_instance();

  static const CapabilityResponse* internal_default_instance();

  void Swap(CapabilityResponse* other);

  // implements Message ----------------------------------------------

  inline CapabilityResponse* New() const { return New(NULL); }

  CapabilityResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CapabilityResponse& from);
  void MergeFrom(const CapabilityResponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CapabilityResponse* other);
  void UnsafeMergeFrom(const CapabilityResponse& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef CapabilityResponse_Recipient Recipient;

  // accessors -------------------------------------------------------

  // optional string application_message_id = 1;
  void clear_application_message_id();
  static const int kApplicationMessageIdFieldNumber = 1;
  const ::std::string& application_message_id() const;
  void set_application_message_id(const ::std::string& value);
  void set_application_message_id(const char* value);
  void set_application_message_id(const char* value, size_t size);
  ::std::string* mutable_application_message_id();
  ::std::string* release_application_message_id();
  void set_allocated_application_message_id(::std::string* application_message_id);

  // repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;
  int recipients_size() const;
  void clear_recipients();
  static const int kRecipientsFieldNumber = 2;
  const ::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient& recipients(int index) const;
  ::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient* mutable_recipients(int index);
  ::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient* add_recipients();
  ::google::protobuf::RepeatedPtrField< ::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient >*
      mutable_recipients();
  const ::google::protobuf::RepeatedPtrField< ::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient >&
      recipients() const;

  // @@protoc_insertion_point(class_scope:agrirouter.response.payload.endpoint.CapabilityResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient > recipients_;
  ::google::protobuf::internal::ArenaStringPtr application_message_id_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto_impl();
  friend void  protobuf_AddDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto_impl();
  friend void protobuf_AssignDesc_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto();
  friend void protobuf_ShutdownFile_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<CapabilityResponse> CapabilityResponse_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CapabilityResponse_Recipient

// optional string id = 1;
inline void CapabilityResponse_Recipient::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CapabilityResponse_Recipient::id() const {
  // @@protoc_insertion_point(field_get:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CapabilityResponse_Recipient::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id)
}
inline void CapabilityResponse_Recipient::set_id(const char* value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id)
}
inline void CapabilityResponse_Recipient::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id)
}
inline ::std::string* CapabilityResponse_Recipient::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CapabilityResponse_Recipient::release_id() {
  // @@protoc_insertion_point(field_release:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CapabilityResponse_Recipient::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.id)
}

// repeated string technical_message_type = 2;
inline int CapabilityResponse_Recipient::technical_message_type_size() const {
  return technical_message_type_.size();
}
inline void CapabilityResponse_Recipient::clear_technical_message_type() {
  technical_message_type_.Clear();
}
inline const ::std::string& CapabilityResponse_Recipient::technical_message_type(int index) const {
  // @@protoc_insertion_point(field_get:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
  return technical_message_type_.Get(index);
}
inline ::std::string* CapabilityResponse_Recipient::mutable_technical_message_type(int index) {
  // @@protoc_insertion_point(field_mutable:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
  return technical_message_type_.Mutable(index);
}
inline void CapabilityResponse_Recipient::set_technical_message_type(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
  technical_message_type_.Mutable(index)->assign(value);
}
inline void CapabilityResponse_Recipient::set_technical_message_type(int index, const char* value) {
  technical_message_type_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
}
inline void CapabilityResponse_Recipient::set_technical_message_type(int index, const char* value, size_t size) {
  technical_message_type_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
}
inline ::std::string* CapabilityResponse_Recipient::add_technical_message_type() {
  // @@protoc_insertion_point(field_add_mutable:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
  return technical_message_type_.Add();
}
inline void CapabilityResponse_Recipient::add_technical_message_type(const ::std::string& value) {
  technical_message_type_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
}
inline void CapabilityResponse_Recipient::add_technical_message_type(const char* value) {
  technical_message_type_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
}
inline void CapabilityResponse_Recipient::add_technical_message_type(const char* value, size_t size) {
  technical_message_type_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
CapabilityResponse_Recipient::technical_message_type() const {
  // @@protoc_insertion_point(field_list:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
  return technical_message_type_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
CapabilityResponse_Recipient::mutable_technical_message_type() {
  // @@protoc_insertion_point(field_mutable_list:agrirouter.response.payload.endpoint.CapabilityResponse.Recipient.technical_message_type)
  return &technical_message_type_;
}

inline const CapabilityResponse_Recipient* CapabilityResponse_Recipient::internal_default_instance() {
  return &CapabilityResponse_Recipient_default_instance_.get();
}
// -------------------------------------------------------------------

// CapabilityResponse

// optional string application_message_id = 1;
inline void CapabilityResponse::clear_application_message_id() {
  application_message_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CapabilityResponse::application_message_id() const {
  // @@protoc_insertion_point(field_get:agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id)
  return application_message_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CapabilityResponse::set_application_message_id(const ::std::string& value) {
  
  application_message_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id)
}
inline void CapabilityResponse::set_application_message_id(const char* value) {
  
  application_message_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id)
}
inline void CapabilityResponse::set_application_message_id(const char* value, size_t size) {
  
  application_message_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id)
}
inline ::std::string* CapabilityResponse::mutable_application_message_id() {
  
  // @@protoc_insertion_point(field_mutable:agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id)
  return application_message_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CapabilityResponse::release_application_message_id() {
  // @@protoc_insertion_point(field_release:agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id)
  
  return application_message_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CapabilityResponse::set_allocated_application_message_id(::std::string* application_message_id) {
  if (application_message_id != NULL) {
    
  } else {
    
  }
  application_message_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), application_message_id);
  // @@protoc_insertion_point(field_set_allocated:agrirouter.response.payload.endpoint.CapabilityResponse.application_message_id)
}

// repeated .agrirouter.response.payload.endpoint.CapabilityResponse.Recipient recipients = 2;
inline int CapabilityResponse::recipients_size() const {
  return recipients_.size();
}
inline void CapabilityResponse::clear_recipients() {
  recipients_.Clear();
}
inline const ::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient& CapabilityResponse::recipients(int index) const {
  // @@protoc_insertion_point(field_get:agrirouter.response.payload.endpoint.CapabilityResponse.recipients)
  return recipients_.Get(index);
}
inline ::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient* CapabilityResponse::mutable_recipients(int index) {
  // @@protoc_insertion_point(field_mutable:agrirouter.response.payload.endpoint.CapabilityResponse.recipients)
  return recipients_.Mutable(index);
}
inline ::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient* CapabilityResponse::add_recipients() {
  // @@protoc_insertion_point(field_add:agrirouter.response.payload.endpoint.CapabilityResponse.recipients)
  return recipients_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient >*
CapabilityResponse::mutable_recipients() {
  // @@protoc_insertion_point(field_mutable_list:agrirouter.response.payload.endpoint.CapabilityResponse.recipients)
  return &recipients_;
}
inline const ::google::protobuf::RepeatedPtrField< ::agrirouter::response::payload::endpoint::CapabilityResponse_Recipient >&
CapabilityResponse::recipients() const {
  // @@protoc_insertion_point(field_list:agrirouter.response.payload.endpoint.CapabilityResponse.recipients)
  return recipients_;
}

inline const CapabilityResponse* CapabilityResponse::internal_default_instance() {
  return &CapabilityResponse_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace endpoint
}  // namespace payload
}  // namespace response
}  // namespace agrirouter

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_messaging_2fresponse_2fpayload_2fendpoint_2fcapability_2eproto__INCLUDED
