// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cloud-provider-integration/cloud-virtualized-app-registration.proto

#ifndef PROTOBUF_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto__INCLUDED
#define PROTOBUF_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "commons/message.pb.h"
// @@protoc_insertion_point(includes)

namespace agrirouter {
namespace cloud {
namespace registration {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();
void protobuf_InitDefaults_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();
void protobuf_AssignDesc_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();
void protobuf_ShutdownFile_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();

class OffboardingRequest;
class OnboardingRequest;
class OnboardingRequest_EndpointRegistrationDetails;
class OnboardingResponse;
class OnboardingResponse_EndpointRegistrationDetails;
class OnboardingResponse_Failures;

// ===================================================================

class OnboardingRequest_EndpointRegistrationDetails : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails) */ {
 public:
  OnboardingRequest_EndpointRegistrationDetails();
  virtual ~OnboardingRequest_EndpointRegistrationDetails();

  OnboardingRequest_EndpointRegistrationDetails(const OnboardingRequest_EndpointRegistrationDetails& from);

  inline OnboardingRequest_EndpointRegistrationDetails& operator=(const OnboardingRequest_EndpointRegistrationDetails& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OnboardingRequest_EndpointRegistrationDetails& default_instance();

  static const OnboardingRequest_EndpointRegistrationDetails* internal_default_instance();

  void Swap(OnboardingRequest_EndpointRegistrationDetails* other);

  // implements Message ----------------------------------------------

  inline OnboardingRequest_EndpointRegistrationDetails* New() const { return New(NULL); }

  OnboardingRequest_EndpointRegistrationDetails* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OnboardingRequest_EndpointRegistrationDetails& from);
  void MergeFrom(const OnboardingRequest_EndpointRegistrationDetails& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OnboardingRequest_EndpointRegistrationDetails* other);
  void UnsafeMergeFrom(const OnboardingRequest_EndpointRegistrationDetails& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto_impl();
  friend void  protobuf_AddDesc_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto_impl();
  friend void protobuf_AssignDesc_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();
  friend void protobuf_ShutdownFile_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<OnboardingRequest_EndpointRegistrationDetails> OnboardingRequest_EndpointRegistrationDetails_default_instance_;

// -------------------------------------------------------------------

class OnboardingRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agrirouter.cloud.registration.OnboardingRequest) */ {
 public:
  OnboardingRequest();
  virtual ~OnboardingRequest();

  OnboardingRequest(const OnboardingRequest& from);

  inline OnboardingRequest& operator=(const OnboardingRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OnboardingRequest& default_instance();

  static const OnboardingRequest* internal_default_instance();

  void Swap(OnboardingRequest* other);

  // implements Message ----------------------------------------------

  inline OnboardingRequest* New() const { return New(NULL); }

  OnboardingRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OnboardingRequest& from);
  void MergeFrom(const OnboardingRequest& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OnboardingRequest* other);
  void UnsafeMergeFrom(const OnboardingRequest& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef OnboardingRequest_EndpointRegistrationDetails EndpointRegistrationDetails;

  // accessors -------------------------------------------------------

  // repeated .agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails onboardingRequests = 1;
  int onboardingrequests_size() const;
  void clear_onboardingrequests();
  static const int kOnboardingRequestsFieldNumber = 1;
  const ::agrirouter::cloud::registration::OnboardingRequest_EndpointRegistrationDetails& onboardingrequests(int index) const;
  ::agrirouter::cloud::registration::OnboardingRequest_EndpointRegistrationDetails* mutable_onboardingrequests(int index);
  ::agrirouter::cloud::registration::OnboardingRequest_EndpointRegistrationDetails* add_onboardingrequests();
  ::google::protobuf::RepeatedPtrField< ::agrirouter::cloud::registration::OnboardingRequest_EndpointRegistrationDetails >*
      mutable_onboardingrequests();
  const ::google::protobuf::RepeatedPtrField< ::agrirouter::cloud::registration::OnboardingRequest_EndpointRegistrationDetails >&
      onboardingrequests() const;

  // @@protoc_insertion_point(class_scope:agrirouter.cloud.registration.OnboardingRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::agrirouter::cloud::registration::OnboardingRequest_EndpointRegistrationDetails > onboardingrequests_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto_impl();
  friend void  protobuf_AddDesc_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto_impl();
  friend void protobuf_AssignDesc_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();
  friend void protobuf_ShutdownFile_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<OnboardingRequest> OnboardingRequest_default_instance_;

// -------------------------------------------------------------------

class OnboardingResponse_EndpointRegistrationDetails : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails) */ {
 public:
  OnboardingResponse_EndpointRegistrationDetails();
  virtual ~OnboardingResponse_EndpointRegistrationDetails();

  OnboardingResponse_EndpointRegistrationDetails(const OnboardingResponse_EndpointRegistrationDetails& from);

  inline OnboardingResponse_EndpointRegistrationDetails& operator=(const OnboardingResponse_EndpointRegistrationDetails& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OnboardingResponse_EndpointRegistrationDetails& default_instance();

  static const OnboardingResponse_EndpointRegistrationDetails* internal_default_instance();

  void Swap(OnboardingResponse_EndpointRegistrationDetails* other);

  // implements Message ----------------------------------------------

  inline OnboardingResponse_EndpointRegistrationDetails* New() const { return New(NULL); }

  OnboardingResponse_EndpointRegistrationDetails* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OnboardingResponse_EndpointRegistrationDetails& from);
  void MergeFrom(const OnboardingResponse_EndpointRegistrationDetails& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OnboardingResponse_EndpointRegistrationDetails* other);
  void UnsafeMergeFrom(const OnboardingResponse_EndpointRegistrationDetails& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional string deviceAlternateId = 2;
  void clear_devicealternateid();
  static const int kDeviceAlternateIdFieldNumber = 2;
  const ::std::string& devicealternateid() const;
  void set_devicealternateid(const ::std::string& value);
  void set_devicealternateid(const char* value);
  void set_devicealternateid(const char* value, size_t size);
  ::std::string* mutable_devicealternateid();
  ::std::string* release_devicealternateid();
  void set_allocated_devicealternateid(::std::string* devicealternateid);

  // optional string sensorAlternateId = 3;
  void clear_sensoralternateid();
  static const int kSensorAlternateIdFieldNumber = 3;
  const ::std::string& sensoralternateid() const;
  void set_sensoralternateid(const ::std::string& value);
  void set_sensoralternateid(const char* value);
  void set_sensoralternateid(const char* value, size_t size);
  ::std::string* mutable_sensoralternateid();
  ::std::string* release_sensoralternateid();
  void set_allocated_sensoralternateid(::std::string* sensoralternateid);

  // optional string capabilityAlternateId = 4;
  void clear_capabilityalternateid();
  static const int kCapabilityAlternateIdFieldNumber = 4;
  const ::std::string& capabilityalternateid() const;
  void set_capabilityalternateid(const ::std::string& value);
  void set_capabilityalternateid(const char* value);
  void set_capabilityalternateid(const char* value, size_t size);
  ::std::string* mutable_capabilityalternateid();
  ::std::string* release_capabilityalternateid();
  void set_allocated_capabilityalternateid(::std::string* capabilityalternateid);

  // optional string endpointId = 5;
  void clear_endpointid();
  static const int kEndpointIdFieldNumber = 5;
  const ::std::string& endpointid() const;
  void set_endpointid(const ::std::string& value);
  void set_endpointid(const char* value);
  void set_endpointid(const char* value, size_t size);
  ::std::string* mutable_endpointid();
  ::std::string* release_endpointid();
  void set_allocated_endpointid(::std::string* endpointid);

  // @@protoc_insertion_point(class_scope:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr devicealternateid_;
  ::google::protobuf::internal::ArenaStringPtr sensoralternateid_;
  ::google::protobuf::internal::ArenaStringPtr capabilityalternateid_;
  ::google::protobuf::internal::ArenaStringPtr endpointid_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto_impl();
  friend void  protobuf_AddDesc_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto_impl();
  friend void protobuf_AssignDesc_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();
  friend void protobuf_ShutdownFile_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<OnboardingResponse_EndpointRegistrationDetails> OnboardingResponse_EndpointRegistrationDetails_default_instance_;

// -------------------------------------------------------------------

class OnboardingResponse_Failures : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agrirouter.cloud.registration.OnboardingResponse.Failures) */ {
 public:
  OnboardingResponse_Failures();
  virtual ~OnboardingResponse_Failures();

  OnboardingResponse_Failures(const OnboardingResponse_Failures& from);

  inline OnboardingResponse_Failures& operator=(const OnboardingResponse_Failures& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OnboardingResponse_Failures& default_instance();

  static const OnboardingResponse_Failures* internal_default_instance();

  void Swap(OnboardingResponse_Failures* other);

  // implements Message ----------------------------------------------

  inline OnboardingResponse_Failures* New() const { return New(NULL); }

  OnboardingResponse_Failures* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OnboardingResponse_Failures& from);
  void MergeFrom(const OnboardingResponse_Failures& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OnboardingResponse_Failures* other);
  void UnsafeMergeFrom(const OnboardingResponse_Failures& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional .agrirouter.commons.Message reason = 2;
  bool has_reason() const;
  void clear_reason();
  static const int kReasonFieldNumber = 2;
  const ::agrirouter::commons::Message& reason() const;
  ::agrirouter::commons::Message* mutable_reason();
  ::agrirouter::commons::Message* release_reason();
  void set_allocated_reason(::agrirouter::commons::Message* reason);

  // @@protoc_insertion_point(class_scope:agrirouter.cloud.registration.OnboardingResponse.Failures)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::agrirouter::commons::Message* reason_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto_impl();
  friend void  protobuf_AddDesc_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto_impl();
  friend void protobuf_AssignDesc_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();
  friend void protobuf_ShutdownFile_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<OnboardingResponse_Failures> OnboardingResponse_Failures_default_instance_;

// -------------------------------------------------------------------

class OnboardingResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agrirouter.cloud.registration.OnboardingResponse) */ {
 public:
  OnboardingResponse();
  virtual ~OnboardingResponse();

  OnboardingResponse(const OnboardingResponse& from);

  inline OnboardingResponse& operator=(const OnboardingResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OnboardingResponse& default_instance();

  static const OnboardingResponse* internal_default_instance();

  void Swap(OnboardingResponse* other);

  // implements Message ----------------------------------------------

  inline OnboardingResponse* New() const { return New(NULL); }

  OnboardingResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OnboardingResponse& from);
  void MergeFrom(const OnboardingResponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OnboardingResponse* other);
  void UnsafeMergeFrom(const OnboardingResponse& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef OnboardingResponse_EndpointRegistrationDetails EndpointRegistrationDetails;
  typedef OnboardingResponse_Failures Failures;

  // accessors -------------------------------------------------------

  // repeated .agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails onboardedEndpoints = 1;
  int onboardedendpoints_size() const;
  void clear_onboardedendpoints();
  static const int kOnboardedEndpointsFieldNumber = 1;
  const ::agrirouter::cloud::registration::OnboardingResponse_EndpointRegistrationDetails& onboardedendpoints(int index) const;
  ::agrirouter::cloud::registration::OnboardingResponse_EndpointRegistrationDetails* mutable_onboardedendpoints(int index);
  ::agrirouter::cloud::registration::OnboardingResponse_EndpointRegistrationDetails* add_onboardedendpoints();
  ::google::protobuf::RepeatedPtrField< ::agrirouter::cloud::registration::OnboardingResponse_EndpointRegistrationDetails >*
      mutable_onboardedendpoints();
  const ::google::protobuf::RepeatedPtrField< ::agrirouter::cloud::registration::OnboardingResponse_EndpointRegistrationDetails >&
      onboardedendpoints() const;

  // repeated .agrirouter.cloud.registration.OnboardingResponse.Failures failures = 2;
  int failures_size() const;
  void clear_failures();
  static const int kFailuresFieldNumber = 2;
  const ::agrirouter::cloud::registration::OnboardingResponse_Failures& failures(int index) const;
  ::agrirouter::cloud::registration::OnboardingResponse_Failures* mutable_failures(int index);
  ::agrirouter::cloud::registration::OnboardingResponse_Failures* add_failures();
  ::google::protobuf::RepeatedPtrField< ::agrirouter::cloud::registration::OnboardingResponse_Failures >*
      mutable_failures();
  const ::google::protobuf::RepeatedPtrField< ::agrirouter::cloud::registration::OnboardingResponse_Failures >&
      failures() const;

  // @@protoc_insertion_point(class_scope:agrirouter.cloud.registration.OnboardingResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::agrirouter::cloud::registration::OnboardingResponse_EndpointRegistrationDetails > onboardedendpoints_;
  ::google::protobuf::RepeatedPtrField< ::agrirouter::cloud::registration::OnboardingResponse_Failures > failures_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto_impl();
  friend void  protobuf_AddDesc_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto_impl();
  friend void protobuf_AssignDesc_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();
  friend void protobuf_ShutdownFile_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<OnboardingResponse> OnboardingResponse_default_instance_;

// -------------------------------------------------------------------

class OffboardingRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agrirouter.cloud.registration.OffboardingRequest) */ {
 public:
  OffboardingRequest();
  virtual ~OffboardingRequest();

  OffboardingRequest(const OffboardingRequest& from);

  inline OffboardingRequest& operator=(const OffboardingRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OffboardingRequest& default_instance();

  static const OffboardingRequest* internal_default_instance();

  void Swap(OffboardingRequest* other);

  // implements Message ----------------------------------------------

  inline OffboardingRequest* New() const { return New(NULL); }

  OffboardingRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OffboardingRequest& from);
  void MergeFrom(const OffboardingRequest& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OffboardingRequest* other);
  void UnsafeMergeFrom(const OffboardingRequest& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string endpoints = 1;
  int endpoints_size() const;
  void clear_endpoints();
  static const int kEndpointsFieldNumber = 1;
  const ::std::string& endpoints(int index) const;
  ::std::string* mutable_endpoints(int index);
  void set_endpoints(int index, const ::std::string& value);
  void set_endpoints(int index, const char* value);
  void set_endpoints(int index, const char* value, size_t size);
  ::std::string* add_endpoints();
  void add_endpoints(const ::std::string& value);
  void add_endpoints(const char* value);
  void add_endpoints(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& endpoints() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_endpoints();

  // @@protoc_insertion_point(class_scope:agrirouter.cloud.registration.OffboardingRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> endpoints_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto_impl();
  friend void  protobuf_AddDesc_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto_impl();
  friend void protobuf_AssignDesc_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();
  friend void protobuf_ShutdownFile_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<OffboardingRequest> OffboardingRequest_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// OnboardingRequest_EndpointRegistrationDetails

// optional string id = 1;
inline void OnboardingRequest_EndpointRegistrationDetails::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OnboardingRequest_EndpointRegistrationDetails::id() const {
  // @@protoc_insertion_point(field_get:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails.id)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingRequest_EndpointRegistrationDetails::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails.id)
}
inline void OnboardingRequest_EndpointRegistrationDetails::set_id(const char* value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails.id)
}
inline void OnboardingRequest_EndpointRegistrationDetails::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails.id)
}
inline ::std::string* OnboardingRequest_EndpointRegistrationDetails::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OnboardingRequest_EndpointRegistrationDetails::release_id() {
  // @@protoc_insertion_point(field_release:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingRequest_EndpointRegistrationDetails::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails.id)
}

// optional string name = 2;
inline void OnboardingRequest_EndpointRegistrationDetails::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OnboardingRequest_EndpointRegistrationDetails::name() const {
  // @@protoc_insertion_point(field_get:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingRequest_EndpointRegistrationDetails::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails.name)
}
inline void OnboardingRequest_EndpointRegistrationDetails::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails.name)
}
inline void OnboardingRequest_EndpointRegistrationDetails::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails.name)
}
inline ::std::string* OnboardingRequest_EndpointRegistrationDetails::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OnboardingRequest_EndpointRegistrationDetails::release_name() {
  // @@protoc_insertion_point(field_release:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingRequest_EndpointRegistrationDetails::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails.name)
}

inline const OnboardingRequest_EndpointRegistrationDetails* OnboardingRequest_EndpointRegistrationDetails::internal_default_instance() {
  return &OnboardingRequest_EndpointRegistrationDetails_default_instance_.get();
}
// -------------------------------------------------------------------

// OnboardingRequest

// repeated .agrirouter.cloud.registration.OnboardingRequest.EndpointRegistrationDetails onboardingRequests = 1;
inline int OnboardingRequest::onboardingrequests_size() const {
  return onboardingrequests_.size();
}
inline void OnboardingRequest::clear_onboardingrequests() {
  onboardingrequests_.Clear();
}
inline const ::agrirouter::cloud::registration::OnboardingRequest_EndpointRegistrationDetails& OnboardingRequest::onboardingrequests(int index) const {
  // @@protoc_insertion_point(field_get:agrirouter.cloud.registration.OnboardingRequest.onboardingRequests)
  return onboardingrequests_.Get(index);
}
inline ::agrirouter::cloud::registration::OnboardingRequest_EndpointRegistrationDetails* OnboardingRequest::mutable_onboardingrequests(int index) {
  // @@protoc_insertion_point(field_mutable:agrirouter.cloud.registration.OnboardingRequest.onboardingRequests)
  return onboardingrequests_.Mutable(index);
}
inline ::agrirouter::cloud::registration::OnboardingRequest_EndpointRegistrationDetails* OnboardingRequest::add_onboardingrequests() {
  // @@protoc_insertion_point(field_add:agrirouter.cloud.registration.OnboardingRequest.onboardingRequests)
  return onboardingrequests_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::agrirouter::cloud::registration::OnboardingRequest_EndpointRegistrationDetails >*
OnboardingRequest::mutable_onboardingrequests() {
  // @@protoc_insertion_point(field_mutable_list:agrirouter.cloud.registration.OnboardingRequest.onboardingRequests)
  return &onboardingrequests_;
}
inline const ::google::protobuf::RepeatedPtrField< ::agrirouter::cloud::registration::OnboardingRequest_EndpointRegistrationDetails >&
OnboardingRequest::onboardingrequests() const {
  // @@protoc_insertion_point(field_list:agrirouter.cloud.registration.OnboardingRequest.onboardingRequests)
  return onboardingrequests_;
}

inline const OnboardingRequest* OnboardingRequest::internal_default_instance() {
  return &OnboardingRequest_default_instance_.get();
}
// -------------------------------------------------------------------

// OnboardingResponse_EndpointRegistrationDetails

// optional string id = 1;
inline void OnboardingResponse_EndpointRegistrationDetails::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OnboardingResponse_EndpointRegistrationDetails::id() const {
  // @@protoc_insertion_point(field_get:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.id)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.id)
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_id(const char* value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.id)
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.id)
}
inline ::std::string* OnboardingResponse_EndpointRegistrationDetails::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OnboardingResponse_EndpointRegistrationDetails::release_id() {
  // @@protoc_insertion_point(field_release:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.id)
}

// optional string deviceAlternateId = 2;
inline void OnboardingResponse_EndpointRegistrationDetails::clear_devicealternateid() {
  devicealternateid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OnboardingResponse_EndpointRegistrationDetails::devicealternateid() const {
  // @@protoc_insertion_point(field_get:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.deviceAlternateId)
  return devicealternateid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_devicealternateid(const ::std::string& value) {
  
  devicealternateid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.deviceAlternateId)
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_devicealternateid(const char* value) {
  
  devicealternateid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.deviceAlternateId)
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_devicealternateid(const char* value, size_t size) {
  
  devicealternateid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.deviceAlternateId)
}
inline ::std::string* OnboardingResponse_EndpointRegistrationDetails::mutable_devicealternateid() {
  
  // @@protoc_insertion_point(field_mutable:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.deviceAlternateId)
  return devicealternateid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OnboardingResponse_EndpointRegistrationDetails::release_devicealternateid() {
  // @@protoc_insertion_point(field_release:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.deviceAlternateId)
  
  return devicealternateid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_allocated_devicealternateid(::std::string* devicealternateid) {
  if (devicealternateid != NULL) {
    
  } else {
    
  }
  devicealternateid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), devicealternateid);
  // @@protoc_insertion_point(field_set_allocated:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.deviceAlternateId)
}

// optional string sensorAlternateId = 3;
inline void OnboardingResponse_EndpointRegistrationDetails::clear_sensoralternateid() {
  sensoralternateid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OnboardingResponse_EndpointRegistrationDetails::sensoralternateid() const {
  // @@protoc_insertion_point(field_get:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.sensorAlternateId)
  return sensoralternateid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_sensoralternateid(const ::std::string& value) {
  
  sensoralternateid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.sensorAlternateId)
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_sensoralternateid(const char* value) {
  
  sensoralternateid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.sensorAlternateId)
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_sensoralternateid(const char* value, size_t size) {
  
  sensoralternateid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.sensorAlternateId)
}
inline ::std::string* OnboardingResponse_EndpointRegistrationDetails::mutable_sensoralternateid() {
  
  // @@protoc_insertion_point(field_mutable:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.sensorAlternateId)
  return sensoralternateid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OnboardingResponse_EndpointRegistrationDetails::release_sensoralternateid() {
  // @@protoc_insertion_point(field_release:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.sensorAlternateId)
  
  return sensoralternateid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_allocated_sensoralternateid(::std::string* sensoralternateid) {
  if (sensoralternateid != NULL) {
    
  } else {
    
  }
  sensoralternateid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sensoralternateid);
  // @@protoc_insertion_point(field_set_allocated:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.sensorAlternateId)
}

// optional string capabilityAlternateId = 4;
inline void OnboardingResponse_EndpointRegistrationDetails::clear_capabilityalternateid() {
  capabilityalternateid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OnboardingResponse_EndpointRegistrationDetails::capabilityalternateid() const {
  // @@protoc_insertion_point(field_get:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.capabilityAlternateId)
  return capabilityalternateid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_capabilityalternateid(const ::std::string& value) {
  
  capabilityalternateid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.capabilityAlternateId)
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_capabilityalternateid(const char* value) {
  
  capabilityalternateid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.capabilityAlternateId)
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_capabilityalternateid(const char* value, size_t size) {
  
  capabilityalternateid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.capabilityAlternateId)
}
inline ::std::string* OnboardingResponse_EndpointRegistrationDetails::mutable_capabilityalternateid() {
  
  // @@protoc_insertion_point(field_mutable:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.capabilityAlternateId)
  return capabilityalternateid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OnboardingResponse_EndpointRegistrationDetails::release_capabilityalternateid() {
  // @@protoc_insertion_point(field_release:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.capabilityAlternateId)
  
  return capabilityalternateid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_allocated_capabilityalternateid(::std::string* capabilityalternateid) {
  if (capabilityalternateid != NULL) {
    
  } else {
    
  }
  capabilityalternateid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), capabilityalternateid);
  // @@protoc_insertion_point(field_set_allocated:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.capabilityAlternateId)
}

// optional string endpointId = 5;
inline void OnboardingResponse_EndpointRegistrationDetails::clear_endpointid() {
  endpointid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OnboardingResponse_EndpointRegistrationDetails::endpointid() const {
  // @@protoc_insertion_point(field_get:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.endpointId)
  return endpointid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_endpointid(const ::std::string& value) {
  
  endpointid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.endpointId)
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_endpointid(const char* value) {
  
  endpointid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.endpointId)
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_endpointid(const char* value, size_t size) {
  
  endpointid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.endpointId)
}
inline ::std::string* OnboardingResponse_EndpointRegistrationDetails::mutable_endpointid() {
  
  // @@protoc_insertion_point(field_mutable:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.endpointId)
  return endpointid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OnboardingResponse_EndpointRegistrationDetails::release_endpointid() {
  // @@protoc_insertion_point(field_release:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.endpointId)
  
  return endpointid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingResponse_EndpointRegistrationDetails::set_allocated_endpointid(::std::string* endpointid) {
  if (endpointid != NULL) {
    
  } else {
    
  }
  endpointid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), endpointid);
  // @@protoc_insertion_point(field_set_allocated:agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails.endpointId)
}

inline const OnboardingResponse_EndpointRegistrationDetails* OnboardingResponse_EndpointRegistrationDetails::internal_default_instance() {
  return &OnboardingResponse_EndpointRegistrationDetails_default_instance_.get();
}
// -------------------------------------------------------------------

// OnboardingResponse_Failures

// optional string id = 1;
inline void OnboardingResponse_Failures::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OnboardingResponse_Failures::id() const {
  // @@protoc_insertion_point(field_get:agrirouter.cloud.registration.OnboardingResponse.Failures.id)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingResponse_Failures::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agrirouter.cloud.registration.OnboardingResponse.Failures.id)
}
inline void OnboardingResponse_Failures::set_id(const char* value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agrirouter.cloud.registration.OnboardingResponse.Failures.id)
}
inline void OnboardingResponse_Failures::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agrirouter.cloud.registration.OnboardingResponse.Failures.id)
}
inline ::std::string* OnboardingResponse_Failures::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:agrirouter.cloud.registration.OnboardingResponse.Failures.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OnboardingResponse_Failures::release_id() {
  // @@protoc_insertion_point(field_release:agrirouter.cloud.registration.OnboardingResponse.Failures.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OnboardingResponse_Failures::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:agrirouter.cloud.registration.OnboardingResponse.Failures.id)
}

// optional .agrirouter.commons.Message reason = 2;
inline bool OnboardingResponse_Failures::has_reason() const {
  return this != internal_default_instance() && reason_ != NULL;
}
inline void OnboardingResponse_Failures::clear_reason() {
  if (GetArenaNoVirtual() == NULL && reason_ != NULL) delete reason_;
  reason_ = NULL;
}
inline const ::agrirouter::commons::Message& OnboardingResponse_Failures::reason() const {
  // @@protoc_insertion_point(field_get:agrirouter.cloud.registration.OnboardingResponse.Failures.reason)
  return reason_ != NULL ? *reason_
                         : *::agrirouter::commons::Message::internal_default_instance();
}
inline ::agrirouter::commons::Message* OnboardingResponse_Failures::mutable_reason() {
  
  if (reason_ == NULL) {
    reason_ = new ::agrirouter::commons::Message;
  }
  // @@protoc_insertion_point(field_mutable:agrirouter.cloud.registration.OnboardingResponse.Failures.reason)
  return reason_;
}
inline ::agrirouter::commons::Message* OnboardingResponse_Failures::release_reason() {
  // @@protoc_insertion_point(field_release:agrirouter.cloud.registration.OnboardingResponse.Failures.reason)
  
  ::agrirouter::commons::Message* temp = reason_;
  reason_ = NULL;
  return temp;
}
inline void OnboardingResponse_Failures::set_allocated_reason(::agrirouter::commons::Message* reason) {
  delete reason_;
  reason_ = reason;
  if (reason) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:agrirouter.cloud.registration.OnboardingResponse.Failures.reason)
}

inline const OnboardingResponse_Failures* OnboardingResponse_Failures::internal_default_instance() {
  return &OnboardingResponse_Failures_default_instance_.get();
}
// -------------------------------------------------------------------

// OnboardingResponse

// repeated .agrirouter.cloud.registration.OnboardingResponse.EndpointRegistrationDetails onboardedEndpoints = 1;
inline int OnboardingResponse::onboardedendpoints_size() const {
  return onboardedendpoints_.size();
}
inline void OnboardingResponse::clear_onboardedendpoints() {
  onboardedendpoints_.Clear();
}
inline const ::agrirouter::cloud::registration::OnboardingResponse_EndpointRegistrationDetails& OnboardingResponse::onboardedendpoints(int index) const {
  // @@protoc_insertion_point(field_get:agrirouter.cloud.registration.OnboardingResponse.onboardedEndpoints)
  return onboardedendpoints_.Get(index);
}
inline ::agrirouter::cloud::registration::OnboardingResponse_EndpointRegistrationDetails* OnboardingResponse::mutable_onboardedendpoints(int index) {
  // @@protoc_insertion_point(field_mutable:agrirouter.cloud.registration.OnboardingResponse.onboardedEndpoints)
  return onboardedendpoints_.Mutable(index);
}
inline ::agrirouter::cloud::registration::OnboardingResponse_EndpointRegistrationDetails* OnboardingResponse::add_onboardedendpoints() {
  // @@protoc_insertion_point(field_add:agrirouter.cloud.registration.OnboardingResponse.onboardedEndpoints)
  return onboardedendpoints_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::agrirouter::cloud::registration::OnboardingResponse_EndpointRegistrationDetails >*
OnboardingResponse::mutable_onboardedendpoints() {
  // @@protoc_insertion_point(field_mutable_list:agrirouter.cloud.registration.OnboardingResponse.onboardedEndpoints)
  return &onboardedendpoints_;
}
inline const ::google::protobuf::RepeatedPtrField< ::agrirouter::cloud::registration::OnboardingResponse_EndpointRegistrationDetails >&
OnboardingResponse::onboardedendpoints() const {
  // @@protoc_insertion_point(field_list:agrirouter.cloud.registration.OnboardingResponse.onboardedEndpoints)
  return onboardedendpoints_;
}

// repeated .agrirouter.cloud.registration.OnboardingResponse.Failures failures = 2;
inline int OnboardingResponse::failures_size() const {
  return failures_.size();
}
inline void OnboardingResponse::clear_failures() {
  failures_.Clear();
}
inline const ::agrirouter::cloud::registration::OnboardingResponse_Failures& OnboardingResponse::failures(int index) const {
  // @@protoc_insertion_point(field_get:agrirouter.cloud.registration.OnboardingResponse.failures)
  return failures_.Get(index);
}
inline ::agrirouter::cloud::registration::OnboardingResponse_Failures* OnboardingResponse::mutable_failures(int index) {
  // @@protoc_insertion_point(field_mutable:agrirouter.cloud.registration.OnboardingResponse.failures)
  return failures_.Mutable(index);
}
inline ::agrirouter::cloud::registration::OnboardingResponse_Failures* OnboardingResponse::add_failures() {
  // @@protoc_insertion_point(field_add:agrirouter.cloud.registration.OnboardingResponse.failures)
  return failures_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::agrirouter::cloud::registration::OnboardingResponse_Failures >*
OnboardingResponse::mutable_failures() {
  // @@protoc_insertion_point(field_mutable_list:agrirouter.cloud.registration.OnboardingResponse.failures)
  return &failures_;
}
inline const ::google::protobuf::RepeatedPtrField< ::agrirouter::cloud::registration::OnboardingResponse_Failures >&
OnboardingResponse::failures() const {
  // @@protoc_insertion_point(field_list:agrirouter.cloud.registration.OnboardingResponse.failures)
  return failures_;
}

inline const OnboardingResponse* OnboardingResponse::internal_default_instance() {
  return &OnboardingResponse_default_instance_.get();
}
// -------------------------------------------------------------------

// OffboardingRequest

// repeated string endpoints = 1;
inline int OffboardingRequest::endpoints_size() const {
  return endpoints_.size();
}
inline void OffboardingRequest::clear_endpoints() {
  endpoints_.Clear();
}
inline const ::std::string& OffboardingRequest::endpoints(int index) const {
  // @@protoc_insertion_point(field_get:agrirouter.cloud.registration.OffboardingRequest.endpoints)
  return endpoints_.Get(index);
}
inline ::std::string* OffboardingRequest::mutable_endpoints(int index) {
  // @@protoc_insertion_point(field_mutable:agrirouter.cloud.registration.OffboardingRequest.endpoints)
  return endpoints_.Mutable(index);
}
inline void OffboardingRequest::set_endpoints(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:agrirouter.cloud.registration.OffboardingRequest.endpoints)
  endpoints_.Mutable(index)->assign(value);
}
inline void OffboardingRequest::set_endpoints(int index, const char* value) {
  endpoints_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:agrirouter.cloud.registration.OffboardingRequest.endpoints)
}
inline void OffboardingRequest::set_endpoints(int index, const char* value, size_t size) {
  endpoints_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:agrirouter.cloud.registration.OffboardingRequest.endpoints)
}
inline ::std::string* OffboardingRequest::add_endpoints() {
  // @@protoc_insertion_point(field_add_mutable:agrirouter.cloud.registration.OffboardingRequest.endpoints)
  return endpoints_.Add();
}
inline void OffboardingRequest::add_endpoints(const ::std::string& value) {
  endpoints_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:agrirouter.cloud.registration.OffboardingRequest.endpoints)
}
inline void OffboardingRequest::add_endpoints(const char* value) {
  endpoints_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:agrirouter.cloud.registration.OffboardingRequest.endpoints)
}
inline void OffboardingRequest::add_endpoints(const char* value, size_t size) {
  endpoints_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:agrirouter.cloud.registration.OffboardingRequest.endpoints)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
OffboardingRequest::endpoints() const {
  // @@protoc_insertion_point(field_list:agrirouter.cloud.registration.OffboardingRequest.endpoints)
  return endpoints_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
OffboardingRequest::mutable_endpoints() {
  // @@protoc_insertion_point(field_mutable_list:agrirouter.cloud.registration.OffboardingRequest.endpoints)
  return &endpoints_;
}

inline const OffboardingRequest* OffboardingRequest::internal_default_instance() {
  return &OffboardingRequest_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace registration
}  // namespace cloud
}  // namespace agrirouter

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cloud_2dprovider_2dintegration_2fcloud_2dvirtualized_2dapp_2dregistration_2eproto__INCLUDED
